### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by pvkas-kevit** [Botmock/kring-exporter#7]
How to re-produce
1. Create board with 1 or 2 steps
2. Create carousal step
3. Add button in carousal

Now doing the export gives internal server error
error occurs at getBoard() method in sdk
same error with APIs too.
`https://app.botmock.com/api/v2/teams/[T_ID]/projects/[P_ID]/boards/[B_ID]`

Tried to create issue at SDK repository but repository is private I think ([npm](https://www.npmjs.com/package/@botmock/client))([repository](https://github.com/Botmock/sdk))

we need it ASAP if possible.

**Comment by obaid** [comment]
We are investigating an API issue. This should be resolved shortly

**Comment by obaid** [comment]
@pvkas-kevit the issue should be fixed now.

**Comment by pvkas-kevit** [comment]
> @pvkas-kevit the issue should be fixed now.

Yes, It is.
Thank you for the quick response.
